"""
App packager service.

Creates downloadable ZIP archives from generated application files.
"""

from __future__ import annotations

import io
import zipfile


class AppPackager:
    """
    Packages generated application files into a downloadable ZIP archive.
    """

    @staticmethod
    def create_zip(
        files: dict[str, str],
        readme_content: str | None = None,
    ) -> bytes:
        """
        Create a ZIP archive from generated files.

        Args:
            files: Mapping of relative file paths to their content.
            readme_content: Optional README content. If provided, added as README.md.

        Returns:
            ZIP file contents as bytes.
        """

        buffer = io.BytesIO()

        with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as zf:
            if readme_content:
                zf.writestr("README.md", readme_content)

            for path, content in sorted(files.items()):
                zf.writestr(path, content)

        return buffer.getvalue()

    @staticmethod
    def build_readme(
        app_name: str,
        description: str,
        tech_stack: dict[str, str] | None = None,
        setup_instructions: list[str] | None = None,
    ) -> str:
        """
        Generate a README.md with setup instructions.

        Args:
            app_name: Name of the application.
            description: Brief description of what the app does.
            tech_stack: Dict of technology choices (e.g., {"frontend": "React"}).
            setup_instructions: Custom setup steps. If None, uses defaults.

        Returns:
            README content as a string.
        """

        lines = [
            f"# {app_name}",
            "",
            description,
            "",
        ]

        if tech_stack:
            lines.append("## Tech Stack")
            lines.append("")
            for key, value in tech_stack.items():
                lines.append(f"- **{key.title()}:** {value}")
            lines.append("")

        if setup_instructions:
            lines.append("## Setup Instructions")
            lines.append("")
            for i, step in enumerate(setup_instructions, 1):
                lines.append(f"{i}. {step}")
            lines.append("")
        else:
            lines.append("## Getting Started")
            lines.append("")
            lines.append("### Prerequisites")
            lines.append("")
            lines.append("Ensure you have the required runtime installed:")
            lines.append("")

            backend = (tech_stack or {}).get("backend", "Python")
            if "python" in backend.lower() or "fastapi" in backend.lower():
                lines.append("```bash")
                lines.append("python --version  # 3.10+")
                lines.append("pip install -r requirements.txt")
                lines.append("```")
            else:
                lines.append("```bash")
                lines.append("node --version  # 18+")
                lines.append("npm install")
                lines.append("```")

            lines.append("")
            lines.append("### Run")
            lines.append("")
            lines.append("```bash")
            lines.append("# Start the development server")
            lines.append("npm run dev")
            lines.append("```")
            lines.append("")

        lines.append("---")
        lines.append("")
        lines.append("*Generated by AI Software Engineering Team*")
        lines.append("")

        return "\n".join(lines)
