"""
Models used by the DevOps agent.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import BaseModel, ConfigDict, Field

if TYPE_CHECKING:
    from ai_team.agents.patches import CodePatch
    from ai_team.shared.enums.devops import DeploymentTarget

# ============================================================================
# Deployment Artifact
# ============================================================================


class DeploymentArtifact(BaseModel):
    """
    Infrastructure artifact generated by the DevOps agent.
    """

    model_config = ConfigDict(
        frozen=True,
        extra="forbid",
    )

    target: DeploymentTarget

    path: str

    description: str

    content: str


# ============================================================================
# Deployment Step
# ============================================================================


class DeploymentStep(BaseModel):
    """
    A deployment or infrastructure step.
    """

    model_config = ConfigDict(
        frozen=True,
        extra="forbid",
    )

    order: int

    title: str

    description: str


# ============================================================================
# Deployment Plan
# ============================================================================


class DeploymentPlan(BaseModel):
    """
    High-level deployment plan.
    """

    model_config = ConfigDict(
        frozen=True,
        extra="forbid",
    )

    summary: str

    steps: list[DeploymentStep] = Field(
        default_factory=list,
    )


# ============================================================================
# DevOps Result
# ============================================================================


class DevOpsResult(BaseModel):
    """
    Result produced by the DevOps agent.
    """

    model_config = ConfigDict(
        frozen=True,
        extra="forbid",
    )

    deployment: DeploymentPlan

    artifacts: list[DeploymentArtifact] = Field(
        default_factory=list,
    )

    code_patches: list[CodePatch] = Field(
        default_factory=list,
    )

    metadata: dict[str, object] = Field(
        default_factory=dict,
    )
